[project]
name = "gopro-xsens"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "opencv-python>=4.13.0.92",
    "xsensdeviceapi",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.20.0",
]

[tool.uv.sources]
xsensdeviceapi = { path = "C:/Program Files/Xsens/MT Software Suite 2022.2/MT SDK/Python/x64/xsensdeviceapi-2022.2.0-cp38-none-win_amd64.whl" }
